ci: hide secrets, change rule to run tests

diff --git a/.github/workflows/karate-testing.yml b/.github/workflows/karate-testing.yml
--- a/.github/workflows/karate-testing.yml
+++ b/.github/workflows/karate-testing.yml
@@ -1,31 +1,43 @@
 name: Karate Local Testing
 
 on:
-  push:
+  pull_request:
     branches:
-      - 'feature/*'
+      - 'master'
 
 env:
   GITHUB_REGISTRY: ghcr.io
 
 jobs:
-  test:
+  local-test-karate:
     # Image to run project and tests
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v4
-    - name: Run service via docker-compose
-      # Run project via docker-compose. 
-      # Use --abort-on-container-exit flag to stop all containers when tests were passed or failed to free up resources.
+    - name: Run service via docker-compose and run Karate-tests
+    # Hide credentials and token from logs, get the number of failed and passed tests
+    # Find text with 'failed' and 'passed' in logs from karate-testing container
+    # Use --abort-on-container-exit flag to stop all containers when tests were passed or failed to free up resources.
       run: |
-        docker-compose up --abort-on-container-exit
-    - name: Extract test results from karate container logs
-      # Extract test results from container logs
-      # We waiting for `passed: <number of passed tests>` in logs
-      run: |
-        FAILED=$(docker-compose logs karate-tests | grep -oP 'failed: *\K\d+')
+        LOGS=$(docker-compose --profile local-run up --abort-on-container-exit)
+        FILTERED_LOGS=$(echo "$LOGS" | sed -E 's/"login":"[^"]*"/"login":"****"/g' \
+                                 | sed -E 's/"password":"[^"]*"/"password":"****"/g' \
+                                 | sed -E 's/"accessToken":[^,}]*"[^"]*"/"accessToken":"****"/g' \
+                                 | sed -E 's/"Authorization":"[^"]*"/"Authorization":"****"/g' \
+                                 | sed -E 's/"X-DEBUG-TOKEN":[^,}]*"[^"]*"/"X-DEBUG-TOKEN":"****"/g' \
+                                 | sed -E 's/accessToken":\{[^}]*\}/accessToken":{"value":"****"}/g' \
+                                 | sed -E 's/X-DEBUG-TOKEN: [^ ]*/X-DEBUG-TOKEN: ****/g') 
+        echo "$FILTERED_LOGS"
+        FAILED=$(echo "$FILTERED_LOGS" | grep -oP 'failed: *\K\d+')
+        PASSED=$(echo "$FILTERED_LOGS" | grep -oP 'passed: *\K\d+')
         echo "Failed tests: $FAILED"
-        if [ $FAILED -gt 0 ]; then
+        echo "Passed tests: $PASSED"
+        if [ "$FAILED" -gt 0 ]; then
           echo "Failed tests found! Failing the pipeline..."
           exit 1
         fi
+        if [ "$PASSED" -eq 0 ]; then
+          echo "No tests passed! Failing the pipeline..."
+          exit 1
+        fi
+
